### ISSUE TITLE
How to change code chunk background in the ResDoc template?

### ISSUE THREAD

**Issue by jordanoplante** [pbs-assess/csasdowntex#144]
Hi,

I would like to add an Appendix where I would explain in detail how a particular analysis was done. Basically, I would like to describe some R code with a mix of normal text, code chunks and results output. To better visualize, I would like the code chunks to have a particular color background. Something like [this](https://stackoverflow.com/questions/17269502/set-code-background-colour-in-r-markdown-to-pdf).

Using the default template for Resdoc, I added the extra argument `pandoc_args` in the `resdoc_pdf` function like this:

```
output:
 csasdown::resdoc_pdf:
   pandoc_args: "--highlight-style=tango"
   french: false
   copy_sty: true
```
When knitting the document, I get an error message saying multiple arguments refer to  `pandoc_args`. 

Can someone help me with this?

Thanks a lot,

J.
